version: '3'
services:
  db:
    image: postgres
    # image: mysql
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      # - ./tmp/db:/var/lib/myql/data
    environment:
      POSTGRES_PASSWORD: password
      # MYSQL_PASSWORD: password
  web:
    build: .
      # context: .
      # dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    # command: bundle exec rails s -p 3000 -b 0.0.0.0
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./:/app
    depends_on:
      - db
    # stdin_open: true
    # tty: true