version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    restart: always
  web:
    build: .
      # context: .
      # dockerfile: ./Dockerfile
    ports:
      - 3000:3000
      - 80:3000
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./:/web
    depends_on:
      - db
    stdin_open: true
    tty: true
    restart: always